### ISSUE TITLE
Wrong Global Patching Commands in Documentation Homepage

### ISSUE THREAD

**Issue by mamei16** [intel/scikit-learn-intelex#1004]
In both the documentation [homepage](https://intel.github.io/scikit-learn-intelex/#usage) and the global patching [page ](https://intel.github.io/scikit-learn-intelex/global-patching.html#global-patching) it is written that the command to install the global patch is   
`python sklearnex.glob patch_sklearn`.   
However, this leads to the error `python: can't open file 'sklearnex.glob': [Errno 2] No such file or directory`. The correct command includes the command line option `-m`, i.e.   
`python -m sklearnex.glob patch_sklearn`  
I'm aware that this isn't a huge issue, but it has irked me since I discovered it two months ago.

**Comment by Alexdruso** [comment]
Just here to say you saved my time :)

**Comment by mamei16** [comment]
> Just here to say you saved my time :)

 I was already thinking I wasted my time writing this issue, since none of the developers seem to care, but I'm happy it was at least helpful to somebody (:

**Comment by PivovarA** [comment]
Hi @mamei16 
Once again, thank you very much for pointing out the inaccuracy in our documentation. 
I created a [PR with a fix](https://github.com/intel/scikit-learn-intelex/pull/1008)
