### ISSUE TITLE
LinearSVC: INFO statements about running accelerated version or falling back to scikit-learn missing

### ISSUE THREAD

**Issue by BethanyL** [intel/scikit-learn-intelex#1012]
**Describe the bug**
When [verbose mode](https://intel.github.io/scikit-learn-intelex/verbose.html) is enabled (e.g. SKLEARNEX_VERBOSE=INFO), INFO statements are printed, such as "SKLEARNEX INFO: sklearn.cluster.DBSCAN.fit: running accelerated version on CPU" or "SKLEARNEX INFO: sklearn.cluster.DBSCAN.fit: fallback to original Scikit-learn." However, these info statements are missing for sklearn.svm.LinearSVC. 

**To Reproduce**
1. [Install](https://github.com/intel/scikit-learn-intelex/blob/master/INSTALL.md) Intel(R) Extension for Scikit-learn. I did:
```
python -m venv intelex
source intelex/bin/activate
pip install scikit-learn-intelex
```
on a Mac (and found the same behavior with a different installation process in Linux)

2. In the terminal:
```
source intelex/bin/activate
export SKLEARNEX_VERBOSE=INFO
python
```

3. In the Python interpreter (although I also saw this bug using a script):
```
from sklearnex import patch_sklearn
patch_sklearn()
from sklearn.svm import LinearSVC
# example adapted from https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVC.html#sklearn.svm.LinearSVC
from sklearn.datasets import make_classification
X, y = make_classification(n_features=4, random_state=0)
clf = LinearSVC(random_state=0, tol=1e-5)
clf.fit(X, y)
```

4. See lack of INFO message.
5. In contrast, continue by importing SVC:
```
from sklearn.svm import SVC
clf = SVC(random_state=0, tol=1e-5)
clf.fit(X, y)
```

6. See INFO message printed:
"SKLEARNEX INFO: sklearn.svm.SVC.fit: running accelerated version on CPU"

**Expected behavior**
I see that SVC support is via sklearn.svm.SVC, not sklearn.svm.LinearSVC, so I'm guessing the fallback message is the expected behavior. I expect to see printed "SKLEARNEX INFO: sklearn.svm.LinearSVC.fit: fallback to original Scikit-learn."

**Environment:**
 - MacOS Monterey 12.4
 - Python 3.7.4
 - scikit-learn 1.0.2
 - scikit-learn-intelex-2021.6.3
 - daal-2021.6.0
 - daal4py-2021.6.3

**Comment by Alexsandruss** [comment]
Thank you for reporting this issue.
It appears that verbose mode logic can confuse users because of no output for unsupported algorithms despite [documentation has one line](https://intel.github.io/scikit-learn-intelex/verbose.html#verbose) for this case: `These print statements are only available for supported algorithms`.
I suppose it should be more highlighted in docs.

**Comment by Alexsandruss** [comment]
Verbose mode is not working for unsupported LinearSVC. It is working for SVC, NuSVC and other supported algorithms.
