### ISSUE TITLE
Has anyone noticed this problem? Cannot import name `sparse_lsqr` from `sklearn.utils.fixes`

### ISSUE THREAD

**Issue by FavorMylikes** [intel/scikit-learn-intelex#1021]
## Reproduce

- env

```env
scikit-learn              1.1.1            py38h6a678d5_0  
scikit-learn-intelex      2021.5.0         py38h06a4308_0
```

```shell
python -m sklearnex.glob patch_sklearn
```

## Log

```log
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (/hidden-path/python3.8/site-packages/sklearn/utils/fixes.py)
```
---

## Explanation

As [Luke369](https://githublab.com/profile/luke396) say
> Latest scikit-learn which works is 1.0.2, so I had to downgrade it

## Question

Should I downgrade it?

## Reference

[scikit-learn-intelex - githublab](https://githublab.com/repository/activity/intel/scikit-learn-intelex)

**Comment by samir-nasibli** [comment]
Hi @FavorMylikes this is bug is already reported. Please see #1007
