### ISSUE TITLE
RuntimeError: Number of rows in numeric table is incorrect

### ISSUE THREAD

**Issue by peterhcyuen** [intel/scikit-learn-intelex#1025]
**Describe the bug**
Failed to fit ridge regression with streaming  = True for a particular batch when the number of rows < number of features in that batch  even if the ridge regression model has already fit on many data points. 

**To Reproduce**
```python
from sklearn.datasets import make_regression
import numpy as np
import daal4py as d4p

dataset = make_regression(n_samples=10000, n_features=20, n_informative=20, n_targets=1, noise=10, random_state=1)
X = dataset[0]
Y = dataset[1]

d4p_algo = d4p.ridge_regression_training(interceptFlag=True, streaming=True)
d4p_algo.compute(X[0:9000], Y[0:9000].reshape(-1, 1))
d4p_algo.compute(X[9000:9002], Y[9000:9002].reshape(-1, 1))
```

**Expected behavior**
Should be able to fit if the d4p_algo has already fit on enough data points from previous batches even if the number of rows < number of features in the current batch.

**Output/Screenshots**
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-124-c460a07da706> in <module>
----> 1 d4p_algo.compute(X[9000:9002], Y[9000:9002].reshape(-1, 1))

build\daal4py_cy.pyx in daal4py._daal4py.ridge_regression_training.compute()

build\daal4py_cy.pyx in daal4py._daal4py._execute_with_context.exec_func()

build\daal4py_cy.pyx in daal4py._daal4py.ridge_regression_training._compute()

RuntimeError: Number of rows in numeric table is incorrect
```

**Environment:**
 - OS: Windows 10
 - Python : 3.6
 - daal4py: 2021.5.4

**Comment by Alexsandruss** [comment]
Case when number of rows is less than number of features is specific even for streaming mode. We will take time to find out is this case meaningful from point of algorithm work.

**Comment by Alexsandruss** [comment]
Input check preventing cases where n_rows < n_features was removed at https://github.com/oneapi-src/oneDAL/pull/2253 and will be included in next oneDAL/daal4py release

**Comment by syakov-intel** [comment]
@peterhcyuen this issue should be fixed in the latest release. Please reopen if the issue persists.
