### ISSUE TITLE
Issue on page /samples/random_forest_yolanda.html

### ISSUE THREAD

**Issue by zhugw** [intel/scikit-learn-intelex#1043]
Why in my compute, it takes so many time
<img width="479" alt="image" src="https://user-images.githubusercontent.com/4953871/189831062-a37d2fcd-725e-476d-8ae3-1bee0da3ecb9.png">
<img width="876" alt="image" src="https://user-images.githubusercontent.com/4953871/189831180-e232b9a6-aa5d-4caa-a584-98d0721e8e9d.png">

```
'Intel® extension for Scikit-learn time: 482.88 s'
```

But in [this page](https://outoftardis.github.io/daal4py/samples/random_forest_yolanda.html), it only takes `42.56s`

**Comment by Alexsandruss** [comment]
Random forest training time heavily depends on number of physical cores. This example notebook highly likely was executed on one of Intel® Xeon® CPUs which has N times more cores than usual desktop CPU. This explains difference of absolute time values while relative speedup is roughly same.

I run this notebook on next CPUs:

| CPU name | Number of cores | Optimized time, s | Stock time, s | Speedup |
| ----------- | ------------------------ | ----------------- | ----------- | ---------- |
| Intel® Core(TM) i7-1185G7 | 4 | 527.61 | 1324.81 | 2.5 |
| Intel® Xeon® Gold 6336Y | 24 x 2 sockets | 53.63 | 138.27 | 2.6 |

**Comment by Alexsandruss** [comment]
Yolanda dataset is quite heavy (280K rows and 100 features) for Random Forest training. If training time is more critical than complexity of model, you can look for linear models: [1](https://github.com/intel/scikit-learn-intelex/blob/master/examples/notebooks/linear_regression.ipynb), [2](https://github.com/intel/scikit-learn-intelex/blob/master/examples/notebooks/lasso_regression.ipynb), [3](https://github.com/intel/scikit-learn-intelex/blob/master/examples/notebooks/ridge_regression.ipynb).
