### ISSUE TITLE
Please sync Anaconda and PyPi versions

### ISSUE THREAD

**Issue by j-adamczyk** [intel/scikit-learn-intelex#1049]
**Describe the bug**

Anaconda and PyPi versions are not the same, which leads to bugs fixed in PyPi version, but not in Anaconda, e.g. [this PR](https://github.com/intel/scikit-learn-intelex/issues/1007), fixing a bug that is important for me.

**To Reproduce**
Create two environments, `venv` and `conda`. In `venv` run `pip install scikit-learn-intelex`, in `conda` run `conda install scikit-learn-intelex`. For example, [this bug](https://github.com/intel/scikit-learn-intelex/issues/1021) will happen in Anaconda version, but not in PyPi version.

**Expected behavior**
Exactly the same code in Anaconda and PyPi.

**Environment:**
 - OS: Ubuntu 22.04
 - Python 3.9

**Comment by pythonic2020** [comment]
I second the motion. intelex from conda causes major problems with conda solving environments (at least those with python 3.9), and isn't compatible with recent versions of scikit-learn.

**Comment by tvdboom** [comment]
Same problem here

**Comment by napetrov** [comment]
Wow, thanks for requests - we would work on updating conda-forge.

**Comment by pythonic2020** [comment]
conda-forge version has been updated!  THANK YOU!!!!!!!!!!!!!!!!!! :-)
