### ISSUE TITLE
Not able to install daal4py 

### ISSUE THREAD

**Issue by imkunals726** [intel/scikit-learn-intelex#1061]
Hey Team,

I'm getting the follwing error while installing daal4py 

 ``` ~ pip3 install daal4py```

```Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement daal4py (from versions: none)
ERROR: No matching distribution found for daal4py
```
Can you guys help?

**Comment by Alexsandruss** [comment]
Hi @imkunals726, highly likely, your platform is not x86 Linux/Windows/MacOS which are currently supported by sklearnex.
Could you specify your OS and hardware, please?

**Comment by Alexsandruss** [comment]
ARM architecture is not supported by daal4py currently.
