### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bbagadd** [intel/scikit-learn-intelex#1065]
Just try your library, so I have a stupid question. Used your sample code to check BrownBoost
How can I get labels for my classification? (I mean 0/1)

Just what I get as a result, in the photo

My sample has values of both 0 and 1
![image](https://user-images.githubusercontent.com/61648347/202784444-ea79c2ba-50ea-49b3-9057-694ee53335da.png)

**Comment by Alexsandruss** [comment]
`predict_result.prediction` is labels produced by classifier

**Comment by bbagadd** [comment]
> `predict_result.prediction` is labels produced by classifier

Yes, I get that. But I rly don't know why model always returns "1".
Where can I read more about supplied parameters, such as "Weaklerner", etc?

**Comment by Alexsandruss** [comment]
Algorithm is explained here a little bit: https://oneapi-src.github.io/oneDAL/daal/algorithms/boosting/brownboost.html
Predicted labels all equal to 1 might be produced because of algorithm way of work and specific data

**Comment by Alexsandruss** [comment]
Brownboost daal4py API: https://intelpython.github.io/daal4py/algorithms.html#brownboost-classification
