### ISSUE TITLE
Missing _classification_model Parameters Info in daal4py Documentation

### ISSUE THREAD

**Issue by raoberman** [intel/scikit-learn-intelex#112]
The daal4py documentation only provides information on the parameter types for the daal4py.decision_forest_classification_model parameters.  There is no other information (purpose, other ranges of values, etc.) on these parameters found in the daal4py documentation or the Intel DAAL Developer Guide. 

This same issue is found for all daal4py algorithms with a model class in the daal4py documentation. 

The documentation should be modified to include the purpose of the model class parameters as well as any other relevant information.

**Comment by napetrov** [comment]
The direct path for this is use of scikit-learn-intelex and relaying on scikit-learn documentation
