### ISSUE TITLE
Python3.11.1 ModuleNotFoundError: No module named 'daal4py._daal4py'

### ISSUE THREAD

**Issue by calculus-ask** [intel/scikit-learn-intelex#1148]
Python version: 3.11.1
ModuleNotFoundError: No module named 'daal4py._daal4py'

**Output/Screenshots**
PS C:\cdc\app> python -m tool.app
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\app\tool\app.py", line 23, in <module>
    from tool.src.routes.croute import api
  File "C:\app\tool\src\Utils\gnkfold.py", line 6, in <module>
    from sklearnex import patch_sklearn
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\__init__.py", line 18, in <module>
    from .dispatcher import patch_sklearn
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\dispatcher.py", line 22, in <module>
    from daal4py.sklearn._utils import daal_check_version, sklearn_check_version
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\daal4py\__init__.py", line 38, in <module>
    from daal4py._daal4py import *
ModuleNotFoundError: No module named 'daal4py._daal4py'

**Environment:**
 - OS: Windows 10
 - Compiler: GCC 9.2
 - Version: 2023.0.0

Packages Installed:
asttokens==2.2.1
attrs==21.2.0
backcall==0.2.0
certifi==2021.10.8
charset-normalizer==2.0.7
click==8.0.3
cloudpickle==2.2.0
cmake==3.25.0
colorama==0.4.4
comm==0.1.2
contourpy==1.0.6
cycler==0.11.0
Cython==0.29.32
daal==2023.0.0
daal4py==2023.0.0
debugpy==1.6.4
decorator==5.1.0
entrypoints==0.4
et-xmlfile==1.1.0
executing==1.2.0
Flask==2.2.2
Flask-HTTPAuth==4.7.0
fonttools==4.38.0
future==0.18.2
greenlet==2.0.1
idna==3.3
importlib-resources==5.4.0
ipykernel==6.19.4
ipython==8.8.0
itsdangerous==2.0.1
jedi==0.18.2
jellyfish==0.9.0
Jinja2==3.1.2
joblib==1.1.0
jsonschema==4.2.1
jupyter_client==7.4.8
jupyter_core==5.1.2
kiwisolver==1.4.4
langid==1.1.6
MarkupSafe==2.1.1
matplotlib==3.6.2
matplotlib-inline==0.1.6
mistune==2.0.4
mysqlclient==2.1.1
nest-asyncio==1.5.6
nltk==3.7
numexpr==2.7.3
numpy==1.24.1
openpyxl==3.0.9
packaging==22.0
pandas==1.5.2
parso==0.8.3
pickleshare==0.7.5
Pillow==9.4.0
platformdirs==2.6.2
plotly==5.10.0
prompt-toolkit==3.0.36
psutil==5.9.4
pure-eval==0.2.2
py4j==0.10.9.5
pybind11==2.10.1
Pygments==2.14.0
PyJWT==2.6.0
PyMySQL==1.0.2
pyparsing==3.0.9
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.3
pywin32==305
PyYAML==6.0
pyzmq==24.0.1
recordlinkage==0.15
regex==2022.10.31
requests==2.26.0
scikit-learn==1.0.1
scikit-learn-intelex==2023.0.0
scikit-multilearn==0.2.0
scipy==1.10.0
six==1.16.0
spyder-kernels==2.4.1
SQLAlchemy==1.4.27
stack-data==0.6.2
tbb==2021.7.1
tenacity==8.1.0
threadpoolctl==3.0.0
tornado==6.2
tqdm==4.63.0
traitlets==5.8.0
urllib3==1.26.7
wcwidth==0.2.5
Werkzeug==2.2.2
wordcloud==1.8.2.post5+gdbf7ab7
zipp==3.6.0

**Comment by Alexsandruss** [comment]
scikit-learn-intelex package for Python 3.10 was installed instead of unreleased version for Python 3.11 resulting in impossibility to load daal4py._daal4py module which is compiled for specific python version.
It's mistake in PyPI packages configuration. I will report it to maintainer of sklearnex packages.

**Comment by Alexsandruss** [comment]
sklearnex/daal4py for Python 3.11 is available in conda-forge: https://anaconda.org/conda-forge/scikit-learn-intelex/files?version=2023.0.1

**Comment by calculus-ask** [comment]
Thank you @Alexsandruss
