### ISSUE TITLE
How should sklearn n_jobs parameter be used with this library?

### ISSUE THREAD

**Issue by smith558** [intel/scikit-learn-intelex#1157]
How should the `n_jobs` parameter (https://scikit-learn.org/stable/glossary.html#term-n_jobs) present in many scikit-learn estimators be used with this library? What's the most optimal use?

**Comment by napetrov** [comment]
and you can find full examples here for controlling threads - https://github.com/intel/scikit-learn-intelex/blob/master/examples/sklearnex/n_jobs.py
