### ISSUE TITLE
"No device of requested type available" exception when running in Github Actions

### ISSUE THREAD

**Issue by Yard1** [intel/scikit-learn-intelex#1158]
**Describe the bug**
We are running sklearnex in PyCaret CI, which uses GithubActions. Since the [2023.0.0](https://github.com/intel/scikit-learn-intelex/releases/tag/2023.0.0) update, running SVM in Github Actions CI causes an exception to be thrown. I cannot reproduce this on my local system. I believe this is either related to some missing enviroment variables, or Github Actions runner hardware setup.

I would appreciate help with working around this issue, and suggestions on how to debug this.

**To Reproduce**
https://github.com/pycaret/pycaret/actions/runs/3921915807/jobs/6704526852

**Expected behavior**
I expect no exceptions.

**Output/Screenshots**
https://github.com/pycaret/pycaret/actions/runs/3921915807/jobs/6704526852

**Environment:**
 - [Github Actions Runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)

**Comment by napetrov** [comment]
@Yard1  - thanks for reporting this.  This error happens for codepath designed for GPU execution via oneAPI, which is wired thing as far PyCaret is intended for CPU only cases. One short thing to try would be 2023.0.1 version which have fixes for dpc_cpp_rt dependency. 

But it's interesting that this problem is get reproduced only for one algorithm and in GithubActions environment.. 

Will look deeper

**Comment by Yard1** [comment]
I believe we are already using 2023.0.1. Thanks for taking the time to look into this!

**Comment by Alexsandruss** [comment]
Device is not available because dpcpp runtimes (`dpcpp-cpp-rt`) are installed but `intelocl` runtime library is not set for usage.
There are two solutions:
- Do not install `dpcpp-cpp-rt` package
or
- Add instruction to use this library:
```bash
sudo mkdir -p /etc/OpenCL/vendors/
sudo bash -c "echo libintelocl.so > /etc/OpenCL/vendors/intel64.icd"
```

**Comment by Alexsandruss** [comment]
Second solution is implemented in https://github.com/pycaret/pycaret/pull/3267
