### ISSUE TITLE
ModuleNotFoundError: No module named 'daal4py._daal4py' in Azure Webapp

### ISSUE THREAD

**Issue by span-11** [intel/scikit-learn-intelex#1159]
Python version: 3.11
I am deploying a flask application on Python 11 (tried also for versions 3.9 and 3.7) , but getting the following error while calling the API : No module named 'daal4py._daal4py'

Output/Screenshots
2023-01-17T04:47:38.924694185Z   File "/tmp/8daf8441ff607f1/app.py", line 3, in <module>
2023-01-17T04:47:38.924698385Z     import daal4py as d4p
2023-01-17T04:47:38.924703785Z   File "/tmp/8daf8441ff607f1/antenv/lib/python3.11/site-packages/daal4py/__init__.py", line 38, in <module>
2023-01-17T04:47:38.924713685Z     from daal4py._daal4py import *
2023-01-17T04:47:38.924718085Z ModuleNotFoundError: No module named 'daal4py._daal4py'
2023-01-17T04:47:38.926140377Z [2023-01-17 04:47:38 +0000] [83] [INFO] Worker exiting (pid: 83)

Environment:
OS: ubuntu
Azure Web App

Packages Installed
daal4py==2023.0.1
scikit-learn-intelex==2023.0.1
flask==2.2.2
pandas==1.5.2
gunicorn==20.1.0

**Comment by Alexsandruss** [comment]
It's expected in case of Python 3.11 because pip mistakenly installs version for 3.10 (mentioned already in https://github.com/intel/scikit-learn-intelex/issues/1148)
@span-11, did you receive exactly same `ModuleNotFoundError: No module named 'daal4py._daal4py'` error on python < 3.11?

**Comment by span-11** [comment]
yes @Alexsandruss I received the same error. 

Also, I am unable to find the daal4py version for python 3.9. Could you suggest me the version for python 3.9?

In Python3.9, 'pip install daal4py' installs 2023.0.1 (which also throws "ModuleNotFoundError: No module named '_daal4py'" error), while installing an older version throws the following error:

(env_test4) C:\Users\xxxx\OneDrive\Desktop>pip install daal4py==2021.6.0
ERROR: Ignored the following versions that require a different python version: 2021.6.0 Requires-Python ==3.10.*; 2021.7.1 Requires-Python ==3.8.*
ERROR: Could not find a version that satisfies the requirement daal4py==2021.6.0 (from versions: 2021.1, 2021.2.0, 2021.2.1, 2021.2.2, 2021.2.3, 2021.3.0, 2021.4.0, 2021.5.0, 2021.5.3, 2021.5.4, 2021.6.2, 2021.6.3, 2021.7.0, 2023.0.0, 2023.0.1)
ERROR: No matching distribution found for daal4py==2021.6.0

**Comment by Alexsandruss** [comment]
Issue wasn't reproduced in my environment, pip installed daal4py/scikit-learn-intelex 2023.0.1 with specification of required version and `daal4py._daal4py` was correctly imported.
Could you provide more environment infom, please? For example, use `platform` builtin python module:
```python
import platform
print(platform.processor(), platform.release(), platform.python_version(), platform.python_implementation(), sep=" | ")
```
