### ISSUE TITLE
[Feature request] Method to detect whether scikit-learn-intelex is enabled

### ISSUE THREAD

**Issue by LucaCappelletti94** [intel/scikit-learn-intelex#1160]
Hello, and thank you for creating this library.

I wanted to detect whether `scikit-learn-intelex` is enabled from the contexts [of a library I work on and uses sklearn models among others](https://github.com/AnacletoLAB/grape), so to suggest to users to install and enable this library when appropriate.

Any approach, such as a method from `scikit-learn-intelex` or a system variable set by the library, would work.

I could not identify whether such a method exists from the library documentation.

Thank you for your time, and have a great day,
Luca

**Comment by Alexsandruss** [comment]
Hello @LucaCappelletti94, [verbose mode](https://intel.github.io/scikit-learn-intelex/verbose.html) shows which implementation of algorithm/function is used.

**Comment by LucaCappelletti94** [comment]
Hello @Alexsandruss, and thank you for the reply. I do not need to set a variable to identify which version is used at run time or get informative logs. I need a way to detect whether a user enables `scikit-learn-intelex` and, if that is not installed or enabled, advise the user to enable it for the relevant models.

Of course, when it is not installed, I can check for the module's existence. For checking whether it is enabled, which options do I have? Again, I need to do this check programmatically rather than by allowing some system variable or by looking at logs.

I hope to have explained myself more clearly.

Thank you for your time,
Luca

**Comment by Alexsandruss** [comment]
Function `sklearnex.sklearn_is_patched` is implemented in #1161 and will be merged soon.
Note: sklearn_is_patched returns False if no arguments are specified and user patched only subset of sklearn functionality because it checks if all patches are applied in that case.

**Comment by LucaCappelletti94** [comment]
Fantastic, can you give me a rough eta of publication of the version with this method available? One month?

**Comment by Alexsandruss** [comment]
> Fantastic, can you give me a rough eta of publication of the version with this method available? One month?

Approximately, two months
