### ISSUE TITLE
conda install daal4py forces a downgrade on the Python

### ISSUE THREAD

**Issue by shailensobhee** [intel/scikit-learn-intelex#121]
Prerequisites state the following:

> Prerequisites
> Python version 2.7 or >= 3.6

However, the problem here is that 3.7 (which is greater than 3.6) is not supported.
`conda install daal4py` forces the python version inside my conda environment to be downgraded from 3.7 to 3.6.8.

**Comment by fschlimb** [comment]
Intel Distribution for Python is still on Python 3.6. Its packges are on the intel channel on anaconda.org. The Intel channel does not provide binaries for Python 3.7. 
To use daal4py with Python 3.7 you currently have to build daal4py from sources. Or wait for Intel Distribution for Python to switch to Python 3.7.

**Comment by napetrov** [comment]
3.7 is supported now.

**Comment by PivovarA** [comment]
Hi @shailensobhee
user can download daal4py using conda-forge channel with 4 python versions: 3.6, 3.7, 3.8, 3.9

**Comment by PetrovKP** [comment]
you can get use daal4py from conda-forge/intel channel and pypi for python3.6 / python 3.7 / python 3.8. more info [here](https://github.com/intel/scikit-learn-intelex#-installation)
