### ISSUE TITLE
Missing tags for 23.1.0 and 23.1.1 

### ISSUE THREAD

**Issue by skupr-anaconda** [intel/scikit-learn-intelex#1239]
**Describe the bug**
The source code is missing tags for 23.1.0 and 23.1.1 https://github.com/intel/scikit-learn-intelex/tags but the corresponding releases are available on pypi https://pypi.org/project/scikit-learn-intelex/#history

**To Reproduce**
1. See https://github.com/intel/scikit-learn-intelex/tags

**Expected behavior**
Tags are available

**Output/Screenshots**

**Environment:**
 - OS: All suported platforms
 - Version: 23.1.0 and 23.1.1

**Comment by Alexsandruss** [comment]
Tags were added:
https://github.com/intel/scikit-learn-intelex/releases/tag/2023.1.0
https://github.com/intel/scikit-learn-intelex/releases/tag/2023.1.1
