### ISSUE TITLE
RuntimeError: Number of columns in input numeric table is incorrect

### ISSUE THREAD

**Issue by Kange2014** [intel/scikit-learn-intelex#1240]
Hi, 

when predicting using a random forests classifier,  it throw out such an error:

File "/lib/python3.9/site-packages/daal4py/sklearn/ensemble/_forest.py", line 312, in _daal_predict_proba
    dfc_predictionResult = dfc_algorithm.compute(X, self.daal_model_)
  File "build/daal4py_cy.pyx", line 17175, in daal4py._daal4py.decision_forest_classification_prediction.compute
  File "build/daal4py_cy.pyx", line 246, in daal4py._daal4py._execute_with_context.exec_func
  File "build/daal4py_cy.pyx", line 17157, in daal4py._daal4py.decision_forest_classification_prediction._compute

RuntimeError: Number of columns in input numeric table is incorrect

Same dataset has been tested successfully using other algorithms, including svm and logit regression. 

Does anyone can provide some hints on this issue? thanks.

**Comment by Alexsandruss** [comment]
@Kange2014, what is the type (numpy.ndarray, pd.DataFrame, etc.) and shape of input data? It's essential to reproduce this issue, and some additional information might be required later.

**Comment by Kange2014** [comment]
Hi @Alexsandruss,

Sorry for a late reply. The input data type is pd.DataFrame, and the shape, for X_train: 232 rows x 146 columns, and for X_val: 59 rows x 146 columns. After fitting the RF model using X_train and y_train successfully, it cannot do predict_proba  on X_val correctly. 

To help reproduce the error, I upload the model and training/validation set as the attached filenames show (unzip it first):
[test_data.zip](https://github.com/intel/scikit-learn-intelex/files/11308900/test_data.zip)

And testing codes:

```
import pandas as pd
import numpy as np
import pickle

from sklearnex import patch_sklearn
patch_sklearn()

from sklearn.ensemble import RandomForestClassifier

X_train = pd.read_csv(f'data_splits/train0.tsv', sep='\t')
X_train = X_train.set_index('sample_id')
X_val = pd.read_csv(f'data_splits/val0.tsv', sep='\t')
X_val = X_val.set_index('sample_id')

f = open(f'data_splits/y_train0.npy', 'rb')
y_train = np.load(f)

f = open('model.pkl','rb')
estimator = pickle.load(f)

estimator.fit(X_train, y_train)
y_probs = estimator.predict_proba(X_val)
```

And error shows:

File "/lib/python3.9/site-packages/daal4py/sklearn/ensemble/_forest.py", line 312, in _daal_predict_proba
    dfc_predictionResult = dfc_algorithm.compute(X, self.daal_model_)
  File "build/daal4py_cy.pyx", line 17175, in daal4py._daal4py.decision_forest_classification_prediction.compute
  File "build/daal4py_cy.pyx", line 246, in daal4py._daal4py._execute_with_context.exec_func
  File "build/daal4py_cy.pyx", line 17157, in daal4py._daal4py.decision_forest_classification_prediction._compute
RuntimeError: Number of columns in input numeric table is incorrect

The running environment is:

python=3.9.16=h7a1cb2a_1
daal4py==2023.1.1
numpy=1.22.3=py39he7a7128_0
pandas=1.5.2=py39h417a72b_0
scikit-learn=1.0.2=py39h51133e4_1

Thanks...

**Comment by Kange2014** [comment]
do we have any updates on this issue?

**Comment by Alexsandruss** [comment]
I run mostly similar code (except loading from 'model.pkl' because it's unsafe to use pickle on externally provided models) and it finished successfully:
```python
import pandas as pd
import numpy as np
import pickle

import logging as lg
lg.getLogger().setLevel(lg.INFO)

from sklearnex import patch_sklearn
patch_sklearn()

from sklearn.ensemble import RandomForestClassifier

X_train = pd.read_csv(f'data_splits/train0.tsv', sep='\t')
X_train = X_train.set_index('sample_id')
X_val = pd.read_csv(f'data_splits/val0.tsv', sep='\t')
X_val = X_val.set_index('sample_id')

y_train = np.load('data_splits/y_train0.npy')

rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train, y_train)
print('training score', rfc.score(X_train, y_train))

with open('model.pkl', 'wb') as mfile:
    pickle.dump(rfc, mfile)

with open('model.pkl', 'rb') as mfile:
    model = pickle.load(mfile)

print(rfc.predict_proba(X_val))
print(model.predict_proba(X_val))
```

**Comment by Kange2014** [comment]
Yes. That's the just strange point. If you build a new model with default parameters, it's ok, as your test show. So here I provide the rfc model, which contains its own custom rfd parameters, as an input.

**Comment by Alexsandruss** [comment]
> Yes. That's the just strange point. If you build a new model with default parameters, it's ok, as your test show. So here I provide the rfc model, which contains its own custom rfd parameters, as an input.

Hi @Kange2014, could you provide your custom Random Forest parameters? I'm not able to load provided model due to [unsafety of `pickle` module](https://docs.python.org/3/library/pickle.html).

**Comment by Alexsandruss** [comment]
Not reproduced.
