### ISSUE TITLE
FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3.

### ISSUE THREAD

**Issue by 2-5** [intel/scikit-learn-intelex#1266]
**Describe the bug**
`dall4py` on fallback is calling the original `sklearn` `RandomForestClassifier` and `RandomForestRegressor` with the deprecated `max_features='auto'` argument:

```python
FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3.
To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is
also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
```

**To Reproduce**
Warning seen when using `scikit-learn-intelex` through `autogluon`

https://github.com/intel/scikit-learn-intelex/blob/eb6676ac100073def15bb4933626e15f4f2d724c/daal4py/sklearn/ensemble/_forest.py#LL649C2-L649C2

**Expected behavior**
No warning

**Versions**
Python 3.10
daal4py-2023.0.1
scikit_learn_intelex-2023.0.1
scikit_learn-1.2.2

**Comment by Alexsandruss** [comment]
[Fixed](https://github.com/intel/scikit-learn-intelex/commit/a09ceef7175707099e4417ac674e786845a72262#diff-d1633e1398300003a1cb5898a97cca1af6ef162666228ec14a94ae917003123eL584) in later releases >= 2023.1.
