### ISSUE TITLE
Building scikit-learn-intelex with openblas/lapack math library with openmp 

### ISSUE THREAD

**Issue by vineel96** [intel/scikit-learn-intelex#1294]
Hi,
Is it possible to build scikit-learn-intelex with openblas or lapack in place of onemkl and openmp in place of onetbb? I could not find any config file for building the library with different math and threading library.

**Comment by Alexsandruss** [comment]
oneMKL and oneTBB are only supported math and threading libraries by underlying ML library (oneDAL).

**Comment by napetrov** [comment]
I would say it's not feasible to replace threading as far TBB and openmp use different approach and code in oneDAL assumes external threading capability such as oneTBB

But for MKL functionality - this is more realistic 
Here is functions export from FPK lib - https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/src/threading/export.def 
They can be mapped to non MKL implementations

**Comment by vineel96** [comment]
Hi @Alexsandruss @napetrov,
1. After installing scikit-learn-intelex, numpy, if i check numpy.show_config() i find its config to be build using openblas. So how MKL is actually linked in intelex? Intelex does not use numpy, scipy on top of MKL? or it uses them in different way?
2. I tired approaches suggested here (https://github.com/IntelPython/composability_bench) where it gives a way to use TBB and mkl based numpy to run scikit learn algorithms. **I did not observe any performance gain in execution time on scikit-learn's kmeans algorithm with tbb monkey patching and intelnumpy(which uses MKL) over normal kmeans algorithm.**
I have installed **intelnumpy, tbb, smp, numba**. I have following doubts:
   3. do TBB monkey patching mimics 100% of oneTBB which is used in onedal(scikit-learn-intelex)? TBB monkey patching is 
       proposed in this paper ( https://conference.scipy.org/proceedings/scipy2016/pdfs/anton_malakhov.pdf)
    4. Based on results can we conclude that oneMKL and oneTBB does not contribute at all for performance gain for kmeans 
        which are major building blocks in scikit-learn-intelex?
As pointed by @napetrov 
5.  mapping to non MKL implementations means, i understand that we need to use openblas or lapack in place of it which means we replace full MKL with openblas or lapack. Am i correct? Also what is full form of fpk?

**Comment by vineel96** [comment]
@napetrov thanks for the reply.
1. So i understand that numpy and scipy dont use MKL when intelex scikit-learn(oneDAL) is used, but oneDAL's algorithms directly use MKL calls. is this correct? Also what is fpk library(full form of fpk)?
2.  You point out that there is no difference in openmp and tbb threading. Is tbb in the paper and oneTBB of onedal are same? if same then what are benefits of oneTBB over openmp? if there is no benefit why openmp is not used in place of oneTBB?
3.  Paper refers as intel TBB which i assume it as oneTBB only, my doubt is that intel TBB which is being referred in paper is same as oneTBB in onedal or different?
4. From your answer, i understand that mkl based numpy and TBB monkey patching is not correct way to use mkl and TBB on stock scikit. Intelex oneDAL does this entirely different without linking MKL to numpy.
5. Ok. Can i know the potential files or areas which needs to be changed to replace all MKL functions with normal BLAS/LAPACK? I wanted to build oneDAL from source on ARM architecture by replacing oneMKL functions as oneMKL wont work on arm. 
Also can u help me in what extra code changes that needs to be done to compile and build oneDAL on ARM?

**Comment by vineel96** [comment]
Hi @napetrov ,
4. you are saying openmp being more performant than oneTBB? Can we expect any performance gain if use BLAS/LAPACK + oneTBB combination ? can u suggest some resources if possible to know gains and shortcommings of using openmp or oneTBB? Also resources to know the entire ecosystem of oneTBB.
5.
   b.) I did profiling (gprof) on intelex's random forest, and i found its using fpk_vsl_kernel_z0_iRngUniform and  fpk_vsl_sub_kernel_z0_dBRngMT19937. Though it dont use any GEMM functions, since it uses **"random number generator"** function from mkl fpk, so how to compile this on ARM? Since mkl fpk "random number generator" is not available on ARM? Any alternative to this function we can use to replace mkl fpk RNG ? 

Also can i know **how to compile only random forest(intelex's)** on ARM?

6. Also in stock sklearn, joblib is used as parallel backend which calls openMP. Does oneTBB replaces joblib+openmp in intelex sklearn?
7.  Observation: when i used intelnumpy (numpy+mkl), profiling (gprof) output of kmeans shows it uses mkl_blas_avx512_dgemm_kernel_nocopy_TN_b0 which is actually different one which oneDAL uses which is fpk_blas_avx512_xdgemm which is fpk version of mkl. So this difference of using **mkl's dgemm and fpk's dgemm**  would effect the performance gain? Do fpk's dgemm as more optimizations leading to more performance gain?

It would be helpful if you could connect folks who are able to port parts to ARM here.  Thanks.

**Comment by napetrov** [comment]
@vineel96 
4. https://community.intel.com/t5/Intel-oneAPI-Threading-Building/TBB-vs-OpenMP/td-p/1103173  In general there are other articles there. but key point - those are different programming models. openMP can deliver higher top perf but at cost of productivity. But again we are talking about < 10% geomean i guess. As an end user you shouldn't bother much about backend threading solution being used.   https://github.com/oneapi-src/oneTBB   TBB is quite popular threading approach and there are millions of monthly downloads. 

5. b) Yes, there would be some use of FPKs libraries.  Here is sort of idea of what you have to replace.
BLAS/LAPACK -> openBLAS
RNGs -> STD lib generators
VML/VSL -> there are open implementations available

So for RNGs you have to use alternative implementation.  Basically as you see this is standard MT19937 which have both generic and ARM optimized implementations. 

6.  joblib sits at higher level and would be calling multiple estimators in parallel. scikit-learn-intelex would do threading on it's onw based on oneDAL without involving joblib. So there is no replacement.  

7. In general there are same level of optimizations between MKL and FPK. At the end for this case FPK just have different prefix to avoid conflicts. then the difference is that oneDAL have different algorithm implementation and likely would be calling different MKL function with different params.  

Yes, would connect once they would be ready.  Should be some update in upcoming weeks if they would be ready to participate.  But bottom line with set of changes on FPK functions replacement and build targets changes they get things running on non Intel platform.

**Comment by vineel96** [comment]
@napetrov Thanks for the detailed explanations.
How to **compile and build** only **intelex's random forest** on ARM? If we replace mkl RNG to with open source RNG, **which file needs to be changed, as RNG used in intelex is from libonedal_core.so file**? Like can i know the detailed steps and files needs to be changed for building intelex's random forest on ARM as a initial start or atleast where to start changing things?

**Comment by napetrov** [comment]
I would suggest to first test steps on x86 

Here are steps for build - https://github.com/oneapi-src/oneDAL/blob/master/INSTALL.md#installation-steps
make -f makefile daal PLAT=lnx32e CORE.ALGORITHMS.CUSTOM="dtrees/forest" REQCPU=avx2 -j16

in terms of RNGs - 
https://github.com/oneapi-src/oneDAL/tree/d21ed3261dc603788a54c07bb943de4ecf9346a1/cpp/daal/src/algorithms/engines/mt19937

**Comment by rakgb-fujitsu** [comment]
@napetrov You've mentioned that few folks were able to compile few parts on arm, any idea what did they replace the functions in `/oneDAL/cpp/daal/src/externals/service_service.h` with?

**Comment by napetrov** [comment]
@KulikovNikita  can comment here

**Comment by KulikovNikita** [comment]
@rakgb-fujitsu Yes, we have [an opened PR](https://github.com/oneapi-src/oneDAL/pull/2396) to support various backends in the oneDAL repository. It can be adjusted to support ARM CPUs. 

The steps needed to be able to run it:
1) Replicate dispatching done in the `cpp/daal/src/algorithms/kernel_inst_x86.h` file with the corresponding ARM CPU families
2) Adjust `makefile`s to support linking with an ARM specific compilation options
3) Modify build scripts in scikit-learn-intelex

What have been done in this PR:
1) Introduced dispatching by backend 
2) Implemented reference algorithms for some of the primitives
3) Implemented a draft implementation of infrastructure to build the library with such backend

Known issues:
1) There will be no bit-to-bit compatibility between results computed on x86 and other backend. It is due to a different RNG backends
2) Be aware about used OpenBLAS library. It can have issues supporting high number of cores

Opened questions:
1) CI support
2) Build distribution

**Comment by rakgb-fujitsu** [comment]
@KulikovNikita this looks good, thanks for sharing this PR. I have a couple of questions:
1) I can see that the backend can choose between "mkl" or "ref", here the "ref" is openblas or something else?
2) Any changes to the build command in order to build this PR? I want to first try this out on x86 with "ref" as backend and openblas support.
3) Since this backend functionality is added, do we still need to handle replacements for RNG, DFT, VSL, SPBLAS calls?

**Comment by KulikovNikita** [comment]
1. Indeed. "Ref" backend options correspond to OpenBLAS calls. I also believe that you need to set up environment variables with path to OpenBLAS installation, etc.
2. Simple versions of these functions/wrappers are already in the library. Feel free to optimize them further with an appropriate substitutions (optimized x-platform libraries).

**Comment by rakgb-fujitsu** [comment]
Yes, I was able to build it with openblas backend. However the regular fpkmkl backend is breaking, I've commented on the PR regarding the same.

**Comment by ajay-fuji** [comment]
Hi @KulikovNikita 
Can you please help with explanation of below code in Makefile - 
`CPUs.files := nrh neh hsw skx` Makefile:[Ln53](https://github.com/oneapi-src/oneDAL/blob/1143b38864ee82e0d80ffcb05d9009272726e3b3/makefile#L53)
`USECPUS.files := $(subst sse2,nrh,$(subst ssse3,,$(subst sse42,neh,$(subst avx,,$(subst avx2,hsw,$(subst avx512,skx,$(subst avx512_mic,,$(USECPUS))))))))`[Ln132](https://github.com/oneapi-src/oneDAL/blob/1143b38864ee82e0d80ffcb05d9009272726e3b3/makefile#L132)
https://github.com/oneapi-src/oneDAL/blob/1143b38864ee82e0d80ffcb05d9009272726e3b3/makefile#L136C1-L140C71
https://github.com/oneapi-src/oneDAL/blob/1143b38864ee82e0d80ffcb05d9009272726e3b3/makefile#L514C1-L520C69`

**Comment by KulikovNikita** [comment]
> Hi @KulikovNikita Can you please help with explanation of below code in Makefile - `CPUs.files := nrh neh hsw skx` Makefile:[Ln53](https://github.com/oneapi-src/oneDAL/blob/1143b38864ee82e0d80ffcb05d9009272726e3b3/makefile#L53) `USECPUS.files := $(subst sse2,nrh,$(subst ssse3,,$(subst sse42,neh,$(subst avx,,$(subst avx2,hsw,$(subst avx512,skx,$(subst avx512_mic,,$(USECPUS))))))))`[Ln132]

According to the GNU Make [official documentation](https://www.gnu.org/software/make/manual/html_node/Text-Functions.html#index-subst-1):

> $(subst from,to,text)
Performs a textual replacement on the text text: each occurrence of from is replaced by to. The result is substituted for the function call.

So it temporarily renames files substituting the most advanced allowed vector extension (`sse2`, `ssse4`, `avx2`, `avx512`) to the proprietary CPU generation naming (`nrh`, `neh`, `hsw`, `skx`). As far as I understand it was done to be able to target very specific generation. 

This step should affect both automatically populated files as well as manually created ones.
