### ISSUE TITLE
Possibility to build daal4py with only one algorithm?

### ISSUE THREAD

**Issue by rakgb-fujitsu** [intel/scikit-learn-intelex#1321]
OneDAL can be compiled for individual algorithms and test them separately, can that built algorithm be used to build daal4py? Doing this lead me to the following runtime error when importing daal4py (after building just kmeans in onedal):

```
>>> from daal4py import kmeans
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/daal4py/__init__.py", line 38, in <module>
    from daal4py._daal4py import *
ImportError: /home/ubuntu/.local/lib/python3.8/site-packages/daal4py/_daal4py.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTIN4daal10algorithms12linear_model10prediction10interface15InputE
```

Is this achievable by just commenting out other algorithms in cython generator files or is more work needed to make this work?

**Comment by Alexsandruss** [comment]
Theoretically, it's possible to remove mentions of other algorithms in [daal4py generator](https://github.com/intel/scikit-learn-intelex/blob/master/generator/gen_daal4py.py#L132) and other places where these algorithms are explicitly mentioned like [this](https://github.com/intel/scikit-learn-intelex/blob/master/src/daal4py.cpp#L916), but it's huge amount of work.
daal4py wasn't designed to use one-algorithm builds of oneDAL.

**Comment by rakgb-fujitsu** [comment]
Thanks for the insights! Closing this thread.
