### ISSUE TITLE
Unable to use sklearnex after building daal4py from source

### ISSUE THREAD

**Issue by rakshithgb-fujitsu** [intel/scikit-learn-intelex#1329]
I built oneDAL from [this PR](https://github.com/oneapi-src/oneDAL/pull/2396), after successfull build I tried to build daal4py and use it. Though daal4py built without any issues, I'm getting error during import:

```
>>> import daal4py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/daal4py/__init__.py", line 38, in <module>
    from daal4py._daal4py import *
ImportError: /home/ubuntu/sandbox/trial_pr/daal/__release_lnx_clang_ref/daal/latest/lib/intel64/libonedal_core.so.1: undefined symbol: sdot_
```

daal4py build:
```
$ export LD_LIBRARY_PATH=/home/ubuntu/sandbox/trial_pr/daal/__release_lnx_clang_ref/daal/latest/lib/intel64:/home/ubuntu/sandbox/trial_pr/daal/__release_lnx_clang_ref/tbb/latest/lib/intel64:/opt/OpenBLAS/lib:$LD_LIBRARY_PATH
$ export DALROOT=/home/ubuntu/sandbox/trial_pr/daal/__release_lnx_clang_ref/daal/latest
$ export NO_DIST=1
$ export NO_STREAM=1
$ export OFF_ONEDAL_IFACE=1
$ python3 setup.py install --single-version-externally-managed --record=record.txt
```

More details on the oneDAL build:
Compiler: clang (10.0.0-4ubuntu1)
Backend (new feature in the PR): ref (uses openblas v0.3.23)

oneDAL build command used:
`make -f makefile daal oneapi_c BACKEND_CONFIG=ref PLAT=lnx32e COMPILER=clang `

I understand this PR brings in a lot of changes, but any clue on how to resolve this would be a great help.

**Comment by icfaust** [comment]
Does compiling oneapi_c without BACKEND_CONFIG=ref and setting that version to DALROOT cause the same undefined symbol?

**Comment by rakgb-fujitsu** [comment]
@icfaust resolved this issue by making few changes in the make file of the PR, it was expecting openblas libs. Daal4py now works without any issues, however building sklearnex I'm now getting runtime errors during patching:

```
Traceback (most recent call last):
  File "/home/ubuntu/sandbox/trial_pr/stock_repo/built_onedal_mkl/lib/python3.8/site-packages/onedal/__init__.py", line 36, in <module>
    import onedal._onedal_py_dpc as _backend
ModuleNotFoundError: No module named 'onedal._onedal_py_dpc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/sandbox/trial_pr/kmeans_daal4py.py", line 38, in <module>
    from sklearnex import patch_sklearn
  File "/home/ubuntu/sandbox/trial_pr/stock_repo/built_onedal_mkl/lib/python3.8/site-packages/sklearnex/__init__.py", line 32, in <module>
    from onedal import _is_dpc_backend
  File "/home/ubuntu/sandbox/trial_pr/stock_repo/built_onedal_mkl/lib/python3.8/site-packages/onedal/__init__.py", line 39, in <module>
    import onedal._onedal_py_host as _backend
ModuleNotFoundError: No module named 'onedal._onedal_py_host' 
```

Tried patching like this:
```
from sklearnex import patch_sklearn
patch_sklearn()
```

Built sklearnex using:
`python3 setup_sklearnex.py install --single-version-externally-managed --record=record.txt`

**Comment by icfaust** [comment]
Try first rebuilding daal4py using the new onedal version (the setup.py command). If that still has the dpc issue, then you will need to compile onedal with 'onedal' instead of 'onedal_c' in the make command.

**Comment by rakgb-fujitsu** [comment]
@icfaust Yup I tried that as well, same issue. I can't compile onedal with 'onedal' option because I'm using gnu/clang compiler. Any workaround or suggestions to resolve the dpc issue?

**Comment by icfaust** [comment]
As I try to figure this out, if you are just using kmeans for the time being you can try to import the daal4py version of kmeans this way

from daal4py.sklearn.cluster import KMeans

I'll get back to you as soon as I look more into this. Let me know if this doesn't work for you temporarily.

**Comment by rakgb-fujitsu** [comment]
@icfaust yup using this temporarily for now, please do let me know if you have any further suggestions.

**Comment by napetrov** [comment]
I think as short term fix you can change code in your version 
https://github.com/intel/scikit-learn-intelex/blob/0b8bfc817db2d1285313298a19913b3fe0e97a92/sklearnex/__init__.py#L53

@samir-nasibli  @Alexsandruss  - looks we've introduced this extra direct dependency in sklernex on oneDAL dpc and we can change code to make this import optional

**Comment by Alexsandruss** [comment]
`sklearnex` is dependent on oneDAL interface, so usage of OFF_ONEDAL_IFACE variable makes its functionality non-working while `daal4py` still works.
If you built `oneapi_c` target of oneDAL, you can unset OFF_ONEDAL_IFACE with any problem.
