### ISSUE TITLE
Speed up customized script

### ISSUE THREAD

**Issue by guozixunnicolas** [intel/scikit-learn-intelex#1342]
Hi there,

I have a custom ML algo similar to: https://github.com/roywright/pu_learning/blob/master/baggingPU.py
It takes decisionTree as the base estimator.

I wonder how can I integrate sckit-learn-intelex framework (e.g., patch) into my custom script? Appreciate your help! 

Best,

Nicolas

**Comment by Alexsandruss** [comment]
Hi Nicolas, none of sklearn functionality in your script can be patched by sklearnex currently.

**Comment by guozixunnicolas** [comment]
Hi Alexander,

Thank you for your reply. In this case I will close the issue. Thank you anyway:)
