### ISSUE TITLE
Longer build time for daal4py with pip

### ISSUE THREAD

**Issue by ajay-fuji** [intel/scikit-learn-intelex#1470]
Build time for daal4py is quite high (approx 5-7 min) due to its single threaded build.
Command - 
`python setup.py install --single-version-externally-managed --record=record.txt`

**Environment:**
 - OS: Ubuntu 22.04
 - Python 3.10
 - machine - 32cores
 
Please suggest how to speed up build process.

**Comment by Alexsandruss** [comment]
daal4py autogenerated wrappers have significant length and sequential dependencies on each other, so it's expected to have long building time.

**Comment by ajay-fuji** [comment]
Ok, Thanks.

**Comment by icfaust** [comment]
I believe the question has been properly answered, and will be closing this issue.
