### ISSUE TITLE
Feature Request - usage of Modin with GPU acceleration

### ISSUE THREAD

**Issue by Master-sniffer** [intel/scikit-learn-intelex#1621]
I am working in Kaggle environment and I encountered an interesting problem: 

Right now, if you use GPU (P100) and run this code: 

```
%pip install "modin[all]" -q

%pip install scikit-learn-intelex -q
```

```
import modin.pandas as mpd
import os
os.environ['MODIN_ENGINE']='Dask'
df=mpd.read_pickle('/input/dataframe.pkl')

y = df['target']

df.drop('target', axis = 1, inplace=True)
X=df

from sklearnex import patch_sklearn,config_context
patch_sklearn()

from sklearn.ensemble import RandomForestClassifier

with config_context(target_offload="gpu:0"):
    rf = RandomForestClassifier(n_jobs=-1, random_state=42) 
    rf.fit(X.values, y.values)

```
I see there is no utilization of GPU. Maybe I am doing something wrong, but I did everything according to documentation.

**Expected behavior**
Usage of GPU for computations

**Environment:**
 - OS: _PRETTY_NAME="Ubuntu 22.04.3 LTS"
    VERSION_ID="22.04"
    VERSION="22.04.3 LTS (Jammy Jellyfish)"_
 - Compiler: _ii  cuda-compiler-11-8                        11.8.0-1                                amd64        CUDA compiler
    ii  g++                                       4:11.2.0-1ubuntu1                       amd64        GNU C++ compiler
    ii  g++-11                                    11.4.0-1ubuntu1~22.04                   amd64        GNU C++ compiler
    ii  gcc                                       4:11.2.0-1ubuntu1                       amd64        GNU C compiler
    ii  gcc-11                                    11.4.0-1ubuntu1~22.04                   amd64        GNU C compiler
    ii  gcc-12                                    12.3.0-1ubuntu1~22.04                   amd64        GNU C compiler
    ii  libllvm15:amd64                           1:15.0.7-0ubuntu0.22.04.3               amd64        Modular compiler and toolchain technologies, runtime library
    ii  libprotoc23:amd64                         3.12.4-1ubuntu7.22.04.1                 amd64        protocol buffers compiler library
    ii  libxkbcommon0:amd64                       1.4.0-1                                 amd64        library interface to the XKB compiler - shared library
    ii  protobuf-compiler                         3.12.4-1ubuntu7.22.04.1                 amd64        compiler for protocol buffer definition files
    ii  rpcsvc-proto                              1.4.2-0ubuntu6                          amd64        RPC protocol compiler and definitions_
 - Version: Python 3.10.12

**Comment by napetrov** [comment]
@Master-sniffer  - scikit-learn-intelex doesn't support Nvidia GPUs, so this is not expected to work. 

Also i guess in this case you just running stock scikit on GPU, for actual GPU offload to intel you have to import from sklearnex
