### ISSUE TITLE
SVR not working with intelex path

### ISSUE THREAD

**Issue by darshanp4** [intel/scikit-learn-intelex#1637]
**Describe the bug**
I tried using SVC and SVR for training and predication, it is observed that SVC uses the oneDAL path but SVR going into default sklearn path. is it known? because in supported algorithm i can see SVR is supported.

**To Reproduce**
1. Setup :  Intel(R) Xeon(R) Platinum 8375C CPU
2. Call : 
from sklearnex import patch_sklearn
patch_sklearn()
    if sys.argv[1]=='svc':
        from sklearn.svm import SVC as SV
    elif sys.argv[1]=='svr':
        from sklearn.svm import SVR as SV

4. Use : 
    sv_params = {"gamma": 'auto'}
    model = SV(**sv_params)
    model.fit(x, y)

6. See error : for SVR 
![image](https://github.com/intel/scikit-learn-intelex/assets/129051745/6f63a2e1-efd5-444d-8954-49cf147e057f)

SVC : 

![image](https://github.com/intel/scikit-learn-intelex/assets/129051745/debbb46f-a876-491e-b9ad-2ea6f2da82ea)

**Expected behavior**
It should use OneDAL path

**Output/Screenshots**
as shown above

**Environment:**
 - Version: 
scikit-learn-intelex     2024.0.1
daal4py                  2024.0.1

**Comment by samir-nasibli** [comment]
@darshanp4 please use [verbose mode](https://github.com/intel/scikit-learn-intelex/blob/0e137ab626994800bb021812ab1afbe8c340a165/examples/sklearnex/verbose_mode.py) for getting more informative logs why you are falling back to stock sklearn.

**Comment by darshanp4** [comment]
@samir-nasibli only seeing following logs on console :

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU

**Comment by darshanp4** [comment]
is verbose supported for SVR ?
seen this issue : https://github.com/intel/scikit-learn-intelex/issues/1012

**Comment by samir-nasibli** [comment]
@darshanp4 thank you for the report. I will investigate and share.

**Comment by Alexsandruss** [comment]
@darshanp4, SVC/SVR with `gamma='auto'` parameter is generally supported in 2024.0.1 version, so I guess the reason is on input data side. Can you share what data type is used for `x` and `y`?

**Comment by samir-nasibli** [comment]
> [data_729para.csv](https://github.com/intel/scikit-learn-intelex/files/13888411/data_729para.csv) attached data file data = pd.read_csv(f"data_729para.csv") x = data.iloc[:, data.columns!='H'].to_numpy() y = data['H'].to_numpy()

@darshanp4 I have checked it with `scikit-learn-intelex 2024.0.1` and `daal4py 2024.0.1`. But can not reproduce your issue. It works fine on my env:
```
daal4py                   2024.0.1         py310_intel_25    intel
numpy                     1.22.4                   pypi_0    pypi
pandas                    2.1.3                    pypi_0    pypi
python                    3.10.13              h955ad1f_0  
scikit-learn              1.3.2                    pypi_0    pypi
scikit-learn-intelex      2024.0.1         py310_intel_25    intel
```
I was using this script for validation:
```python
import logging

import numpy as np
import pandas as pd


logging.getLogger("sklearnex").setLevel(logging.INFO)

data = pd.read_csv("../data.csv")

from sklearnex import patch_sklearn

patch_sklearn()

X = data.iloc[:, data.columns!='H'].to_numpy()
y = data['H'].to_numpy()
print("x data type: ", X.dtype)
print("y data type: ", y.dtype)

from sklearn.svm import SVR
sv_params = {"gamma": 'auto'}
model = SVR(**sv_params)
model.fit(X, y)

```

Output:
```
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
x data type:  float64                                      
y data type:  int64                                              
INFO:sklearnex: sklearn.svm.SVR.fit: running accelerated version on CPU
```

**Comment by darshanp4** [comment]
That verbose output I also see on console, but did you check that it actually using accelerated oneDAL. If you profile it uses the stock. That's what I reported initial. Can you paste the perf report as well of your run? To confirm it uses the intelex version.

**Comment by darshanp4** [comment]
okay thanks for verifying , I will recheck from end and update.

**Comment by darshanp4** [comment]
Sorry for late update , issue was due to using below flag

# os.environ['NO_DIST']='1'
# os.environ['NO_STREAM']='1'
# os.environ['OFF_ONEDAL_IFACE']='1'
