### ISSUE TITLE
Unable to run patch_sklearn()

### ISSUE THREAD

**Issue by briankw1108** [intel/scikit-learn-intelex#1680]
**Describe the bug**
I updated it to the latest version of 2024.1.0, but I got an error when I tried to run `patch_sklearn()` after importing `patch_sklearn` from `sklearnex`.

The error message says that: AttributeError: module 'threadpoolctl' has no attribute 'ThreadpoolController'

**To Reproduce**
1. pip install scikit-learn-intelex
2. `from sklearnex import patch_sklearn`
3. run `patch_sklearn()`
4. AttributeError: module 'threadpoolctl' has no attribute 'ThreadpoolController'

**Expected behavior**
Able to enable patching

**Output/Screenshots**
![image](https://github.com/intel/scikit-learn-intelex/assets/12106472/e87987b5-699f-4e98-9ad9-9f3a973a9ae1)

**Environment:**
 - Databricks Runtime Version 13.3
 - Python 3.10.12

**Comment by Alexsandruss** [comment]
threadpoolctl is dependency of scikit-learn and scikit-learn-intelex and definitely contains ThreadpoolController.
This issue is highly likely on environment side.
