### ISSUE TITLE
INFO

### ISSUE THREAD

**Issue by KnSun99** [intel/scikit-learn-intelex#1695]
How do I turn off the printing of messages like the following？

sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
sklearn.utils.validation._assert_all_finite: running accelerated version on CPU

**Comment by ethanglaser** [comment]
Hello, you should be able to resolve this by setting `SKLEARNEX_VERBOSE` to the desired level of verbosity. See our docs: https://intel.github.io/scikit-learn-intelex/latest/verbose.html and python logging: https://docs.python.org/3/howto/logging.html for further details. Try setting to `WARNING` or `ERROR` for reduced verbosity.

**Comment by Alexsandruss** [comment]
Alternative way to return default level of logging in script:
```python
import logging
logging.getLogger('sklearnex').setLevel("WARNING")
```

**Comment by KnSun99** [comment]
Thank you for your reply!
I'll have a try.
