### ISSUE TITLE
Logistic regression running with n_jobs=-1

### ISSUE THREAD

**Issue by darshanp4** [intel/scikit-learn-intelex#1709]
**Describe the bug**
I am trying to run the logistic regression and seeing in to the logs that it is falling back to stock scikit-learn and then running accelerated version on CPU, is it expected bahaviour that as i am expecting to get only run on accelerated version.

**To Reproduce**
1. Setup 
script used for running
lr.py
=============================================================
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from timeit import default_timer as timer

from sklearnex import patch_sklearn
patch_sklearn()

import logging
logging.getLogger("sklearnex").setLevel(logging.INFO)
# Generate Dataset
X, y = make_classification(n_samples=10000000, 
                            n_features=20, 
                            n_classes=2, 
                            random_state=42)

# Main
num_runs = 1  # Number of runs
elapsed_times = []

for _ in range(num_runs):
    start = timer()
    model = LogisticRegression()
    model.fit(X, y)
    elapsed = timer() - start
    elapsed_times.append(elapsed)

# Calculate average elapsed time
avg_time = sum(elapsed_times) / num_runs
print(f"Elapsed time list: {elapsed_times}")
print(f"Average time over {num_runs} runs: {avg_time} seconds")
=======================================================================
3. Call : python3 lr.py
5. Use 
'scikit-learn-intelex     2024.0.1
daal4py                  2024.0.1
7. See error
python3 lr.py 
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
**INFO:sklearnex: sklearn.utils.validation._assert_all_finite: fallback to original Scikit-learn
INFO:sklearnex: sklearn.linear_model.LogisticRegression.fit: running accelerated version on CPU**
Elapsed time list: [0.9992906190000213]
Average time over 1 runs: 0.9992906190000213 seconds
**Expected behavior**
only running on accelerated version

**Output/Screenshots**
output as shown above

**Environment:**
 - OS: Ubuntu 22.04.2
- Hardware : Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz

**Comment by Alexsandruss** [comment]
It's expected behavior: `y` is of `int` type which is not checked by scikit-learn-intelex. `X` is processed as expected.
DEBUG logging level explains it:
```
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
DEBUG:sklearnex: sklearn.utils.validation._assert_all_finite: debugging for the patch is enabled to track the usage of Intel® oneAPI Data Analytics Library (oneDAL)
DEBUG:sklearnex: sklearn.utils.validation._assert_all_finite: patching failed with cause - X dtype is not float32 or float64.
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: fallback to original Scikit-learn
```
LogisticRegression is trained with patching:
```
INFO:sklearnex: sklearn.linear_model.LogisticRegression.fit: running accelerated version on CPU
```

**Comment by darshanp4** [comment]
@Alexsandruss can we see similar logs for predict as well?

as in my run if i add predict 
model.predict(X) 

i see only 

INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
how to confirm if this also running using sklearnex?

**Comment by darshanp4** [comment]
@Alexsandruss but the X dtype shows float64 only. still it prints :

DEBUG:sklearnex: sklearn.utils.validation._assert_all_finite: patching failed with cause - X dtype is not float32 or float64.

**Comment by darshanp4** [comment]
@Alexsandruss i am getting the issue when n_jobs is -1 , it is not trained with patching.

if we add the below param to above script in issue 
model = LogisticRegression( tol = 0,
            C = 0.1,
            multi_class = "multinomial",
            solver = "lbfgs",
            n_jobs = -1)

if we keep default or n_jobs=1 then only i see : 
INFO:sklearnex: sklearn.linear_model.LogisticRegression.fit: running accelerated version on CPU

**Comment by darshanp4** [comment]
@Alexsandruss could you please help to look at the above issue?

**Comment by Alexsandruss** [comment]
This code with `n_jobs=-1` works normally for sklearnex 2024.1.0:

```python
from sklearnex.linear_model import LogisticRegression
from sklearn.datasets import make_classification
import logging as lg


lg.getLogger("sklearnex").setLevel("INFO")

x, y = make_classification(
    n_samples=200000,
    n_features=128,
    random_state=42
)
lr = LogisticRegression(
    tol=0,
    C=0.1,
    multi_class="multinomial",
    solver="lbfgs",
    n_jobs=-1
).fit(x, y)
print("Score:", lr.score(x, y))
```

Output:
```
INFO:sklearnex: sklearn.linear_model.LogisticRegression.fit: running accelerated version on CPU
INFO:sklearnex: sklearn.linear_model.LogisticRegression.predict: running accelerated version on CPU
Score: 0.924205
```

**Comment by darshanp4** [comment]
thanks @Alexsandruss for checking it, but if we use patching 
```
from sklearnex import patch_sklearn
patch_sklearn()
```
then this issue is seen.

With direct import of `from sklearnex.linear_model import LogisticRegression` issue is not seen.

**Comment by darshanp4** [comment]
can you keep reopen the issue ? it will helpful.

**Comment by darshanp4** [comment]
```
from sklearn.linear_model import LogisticRegression
from sklearnex import patch_sklearn
patch_sklearn()
# from sklearnex.linear_model import LogisticRegression
from sklearn.datasets import make_classification
import logging as lg


lg.getLogger("sklearnex").setLevel("INFO")

x, y = make_classification(
    n_samples=200000,
    n_features=128,
    random_state=42
)
lr = LogisticRegression(
    tol=0,
    C=0.1,
    multi_class="multinomial",
    solver="lbfgs",
    n_jobs=-1
).fit(x, y)
print("Score:", lr.score(x, y))
```

This is the exact reproducer with the script you mentioned.
Basically we import sklearn Logistic regression and use patch with n_jobs=-1, not running with patch.

if you import sklearnex it is working fine, so seems like some issue with patch.

**Comment by Alexsandruss** [comment]
LogisticRegression import should be after patching

![image](https://github.com/intel/scikit-learn-intelex/assets/24354279/9b729d7c-1baf-4d83-bed4-d1f8a6fd622b)

**Comment by darshanp4** [comment]
Thank you @Alexsandruss for all your quick help.
