### ISSUE TITLE
DPC backend error on Windows

### ISSUE THREAD

**Issue by purohitank** [intel/scikit-learn-intelex#1746]
Hello,

I am trying to use this package in Windows 11 in a virtual environment.

I tried to run a test script but got the following errors. Also, listing the environments I see dpcpp-cpp-rt is installed. Please find below the logs. I had run the same test successfully in WSL. Thank you in advance for your help

(ipex_env) D:\scikit_test>python test.py
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
Traceback (most recent call last):
  File "D:\scikit_test\test.py", line 11, in <module>
    clustering = DBSCAN(eps=3, min_samples=2).fit(X)
  File "C:\Users\ankit\AppData\Local\conda\conda\envs\ipex_env\lib\site-packages\sklearnex\cluster\dbscan.py", line 176, in fit
    dispatch(
  File "C:\Users\ankit\AppData\Local\conda\conda\envs\ipex_env\lib\site-packages\sklearnex\_device_offload.py", line 189, in dispatch
    return branches[backend](obj, *hostargs, **hostkwargs, queue=q)
  File "C:\Users\ankit\AppData\Local\conda\conda\envs\ipex_env\lib\site-packages\daal4py\sklearn\_utils.py", line 392, in method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\ankit\AppData\Local\conda\conda\envs\ipex_env\lib\site-packages\sklearnex\cluster\dbscan.py", line 100, in _onedal_fit
    self._onedal_estimator.fit(X, y=y, sample_weight=sample_weight, queue=queue)
  File "C:\Users\ankit\AppData\Local\conda\conda\envs\ipex_env\lib\site-packages\onedal\cluster\dbscan.py", line 112, in fit
    return super()._fit(X, y, sample_weight, _backend.dbscan.clustering, queue)
  File "C:\Users\ankit\AppData\Local\conda\conda\envs\ipex_env\lib\site-packages\onedal\cluster\dbscan.py", line 64, in _fit
    policy = self._get_policy(queue, X)
  File "C:\Users\ankit\AppData\Local\conda\conda\envs\ipex_env\lib\site-packages\onedal\cluster\dbscan.py", line 51, in _get_policy
    return _get_policy(queue, *data)
  File "C:\Users\ankit\AppData\Local\conda\conda\envs\ipex_env\lib\site-packages\onedal\common\_policy.py", line 36, in _get_policy
    raise RuntimeError(
RuntimeError: Operation using the requested SYCL queue requires the DPC backend

# Name                    Version                   Build  Channel
bzip2                     1.0.8                he774522_0
ca-certificates           2023.12.12           haa95532_0
daal                      2024.1.0                  <pip>
daal4py                   2024.1.0                  <pip>
dpcpp-cpp-rt              2024.0.0                  <pip>
dpctl                     0.15.0                    <pip>
dpnp                      0.13.0                    <pip>
intel-cmplr-lib-rt        2024.0.0                  <pip>
intel-cmplr-lic-rt        2024.0.0                  <pip>
intel-opencl-rt           2024.0.0                  <pip>
intel-openmp              2024.0.0                  <pip>
joblib                    1.3.2                     <pip>
libffi                    3.4.4                hd77b12b_0
mkl                       2024.0.0                  <pip>
mkl-dpcpp                 2024.0.0                  <pip>
mkl-fft                   1.3.8                     <pip>
mkl-random                1.2.4                     <pip>
mkl-service               2.4.0                     <pip>
mkl-umath                 0.1.1                     <pip>
numpy                     1.24.4                    <pip>
onemkl-sycl-blas          2024.0.0                  <pip>
onemkl-sycl-datafitting   2024.0.0                  <pip>
onemkl-sycl-dft           2024.0.0                  <pip>
onemkl-sycl-lapack        2024.0.0                  <pip>
onemkl-sycl-rng           2024.0.0                  <pip>
onemkl-sycl-sparse        2024.0.0                  <pip>
onemkl-sycl-stats         2024.0.0                  <pip>
onemkl-sycl-vm            2024.0.0                  <pip>
openssl                   3.0.13               h2bbff1b_0
pip                       23.3.1          py310haa95532_0
python                    3.10.13              he1021f5_0
scikit-learn              1.4.1.post1               <pip>
scikit-learn-intelex      2024.1.0                  <pip>
scipy                     1.12.0                    <pip>
setuptools                68.2.2          py310haa95532_0
six                       1.16.0                    <pip>
sqlite                    3.41.2               h2bbff1b_0
tbb                       2021.11.0                 <pip>
tbb4py                    2021.11.0                 <pip>
threadpoolctl             3.3.0                     <pip>
tk                        8.6.12               h2bbff1b_0
tzdata                    2024a                h04d1e81_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.41.2          py310haa95532_0
xz                        5.4.5                h8cc25b3_0
zlib                      1.2.13               h8cc25b3_0

**Comment by Alexsandruss** [comment]
This Windows-specific issue was fixed in https://github.com/intel/scikit-learn-intelex/commit/805b7b881298a0eac6962e35127e0be039e228a3 and will be included in future release.
