### ISSUE TITLE
How to build scikit-learn-intelex from source

### ISSUE THREAD

**Issue by wswsmao** [intel/scikit-learn-intelex#1747]
Hi, I have read the doc below
https://intel.github.io/scikit-learn-intelex/latest/index.html

is there any way to build scikit-learn-intelex from source？

**Comment by Alexsandruss** [comment]
Firstly, you need to [build daal4py from source](https://github.com/intel/scikit-learn-intelex/blob/main/daal4py/INSTALL.md) or install it from any supported distribution channel. Then, you can [install sklearnex from source](https://intel.github.io/scikit-learn-intelex/latest/installation.html#build-from-sources).
