### ISSUE TITLE
Intel conda channel is not accessible

### ISSUE THREAD

**Issue by ryan-rozario** [intel/scikit-learn-intelex#1913]
**Describe the bug**
Installing packages from intel conda channel returns 
UnavailableInvalidChannel: HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>

**To Reproduce**
1. Run
conda install -c intel intel-openmp
2. Output
UnavailableInvalidChannel: HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>
The channel is not accessible or is invalid.

**Expected behavior**
Channel is accessible

**Comment by napetrov** [comment]
thanks - recommendation would be to use conda-forge 

conda install -c conda-forge intel-openmp

**Comment by ryan-rozario** [comment]
Channel is accessible again

**Comment by A-Infor** [comment]
> Channel is accessible again

It is not anymore.
