### ISSUE TITLE
Anaconda Intel Channel 403's

### ISSUE THREAD

**Issue by AcylSilane** [intel/scikit-learn-intelex#1935]
**Describe the bug**
Currently, when one attempts to install the package via `conda install -c intel scikit-learn-intelex`, an HTTP 403 is returned and installation is impossible.

This appears to have also happened last week (see https://github.com/intel/scikit-learn-intelex/issues/1913), and the comment chain states the channel had been made accessible again.
Today, an associated PR (see https://github.com/intel/scikit-learn-intelex/pull/1932) was merged to fix the issue.

I experienced this a few minutes ago (16 hours after that branch was merged), and haven't tried installing from this channel in about 2 weeks. So, I can't comment on whether this is related to the same problem(s) the issue and PR discuss, or if it is a new problem.

I tested this on 2 separate computers and 2 separate internet connections (with and without a VPN), to confirm it wasn't isolated to just one machine/network.

**To Reproduce**
1. Open up a terminal and activate anaconda (or miniconda)
2. Run `conda install -c intel scikit-learn-intelex`
3. Anaconda will fail due to a 403.

**Expected behavior**
Conda reports that the package exists or not, but it shouldn't 403.

**Output/Screenshots**
```
❯ conda install scikit-learn-intelex
Retrieving notices: ...working... done
Channels:
 - defaults
 - intel
Platform: win-64
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

**Environment:**
 - OS: Win11 (also reproduces on WSL Debian on both machines I tried this on)
 - Compiler: N/A
 - Version: Conda 23.7.4

**Comment by napetrov** [comment]
Bee free to use conda-forge channel - i do have latest bits there.

**Comment by ryan-rozario** [comment]
@napetrov Could you please look into why the intel channel is not accessible. If this is not the correct forum could you raise the issue in the correct forum.
The intel channel has not been accessible again since 11th July.

We use some packages which are not in the conda-forge channel like intelpython which are not available in conda forge.

**Comment by napetrov** [comment]
@ryan-rozario  - there is Intel hosted channel available, please look at https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2024-2/conda.html

**Comment by BPLive** [comment]
Dear all, 

If I'm not mistaken, until 'Intel Channel 403' error have appeared, the update to the latest version of Intel Scikit Learn Intelex included a whl file. Please confirm if yes or no, and if the file was indeed present, can you please tell me how can I update it too? Also, as you can see from the attached txt file, the '403' error continues to occur. Is there any way to prevent this error from appearing during the update process?

Thanks in advance for your attention. 
Best regards!
[Intel Scikit Learn Intelex - Installation.txt](https://github.com/user-attachments/files/17397988/Intel.Scikit.Learn.Intelex.-.Installation.txt)

**Comment by napetrov** [comment]
@BPLive  - you need to completely remove intel channel from channels list. please follow instructions here -  https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2024-2/conda.html

scikit whl packages are part of pypi https://pypi.org/project/scikit-learn-intelex/
