### ISSUE TITLE
Can't convert LGBMClassifier with daal4py

### ISSUE THREAD

**Issue by GLmontanari** [intel/scikit-learn-intelex#2006]
**Describe the bug**
I am trying to accelerate a LGBMClassifier model on CPU but I can't. I have tried different ways:

**To Reproduce**
This is my code
```
import lightgbm as lgb
import daal4py as d4p

# Then I have a section where I load the data
# ...

# This is not working
lgb_model = lgb.LGBMClassifier(num_leaves=31).fit(x_train, y_train)
daal_model = d4p.get_gbt_model_from_lightgbm(lgb_model)  # AttributeError: 'LGBMClassifier' object has no attribute 'dump_model'

# I don't know the difference (yet), but this is working
lgb_model = lgb.train({'num_leaves': 31}, lgb.Dataset(x_train, y_train))
daal_model = d4p.get_gbt_model_from_lightgbm(lgb_model)

# Unfortunately, when I test on the test set, this method returns
# 1: float labels instead of integers (I want to do multiclass classification)
# 2: the results are different from the non-optimized LGBMClassifier, in particular they are worse
```

**Output/Screenshots**
Upon converting the model with this line `d4p.get_gbt_model_from_lightgbm(lgb_model)` I get an exception:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2024.1.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1535, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2024.1.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\MiniProgetti\SEA_ML_BENCHMARKS\sklearn_benchmarks\TestIntel.py", line 90, in <module>
    d4p.get_gbt_model_from_lightgbm(lgb_model)  # AttributeError: 'LGBMClassifier' object has no attribute 'dump_model'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build\\daal4py_cy.pyx", line 21558, in daal4py._daal4py.get_gbt_model_from_lightgbm
AttributeError: 'LGBMClassifier' object has no attribute 'dump_model'
```
I have tried also daal4py 2023.2.0 and daal4py 2023.2.1 and get a different exception:
```
Traceback (most recent call last):
  File "C:\Users\iicgym\AppData\Local\Programs\Python\Python311\Lib\timeit.py", line 180, in timeit
    timing = self.inner(it, self.timer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<timeit-src>", line 7, in inner
  File "build\\daal4py_cy.pyx", line 21576, in daal4py._daal4py.get_gbt_model_from_lightgbm
  File "build\\daal4py_cy.pyx", line 21445, in daal4py._daal4py.TreeList.from_lightgbm_booster_dump
  File "build\\daal4py_cy.pyx", line 21353, in daal4py._daal4py.Node.from_lightgbm_dict
KeyError: 'leaf_count'
python-BaseException
```

**Environment:**
 - OS: Windows10
 - Python 3.11.9
 - daal4py 2024.5.0 
 - sklearn-intelex 2024.5.0
 - lightgbm 4.5.0 (tried also 4.3.0)

**Comment by syakov-intel** [comment]
Hi! Thanks for the report, we'll investigate it.

**Comment by razdoburdin** [comment]
Hi @GLmontanari ,
thanks for using daal4py!

The root of the problem is that the API you chose doesn't support scikit-learn estimators like `LGBMClassifier`. To resolve this, you need to switch to a newer version of the API. Please take a look at [the example ](https://github.com/intel/scikit-learn-intelex/blob/4fd45689a9fc998c2f3228d4b066bf0e1aa04bf0/examples/mb/model_builders_lightgbm.py#L69) or [the paper](https://www.intel.com/content/www/us/en/developer/articles/technical/faster-xgboost-light-gbm-catboost-inference-on-cpu.html).

**Comment by GLmontanari** [comment]
I am sharing with you an excerpt of `pip list`
```
...
daal                      2024.5.0
daal4py                   2024.5.0
...
dpcpp-cpp-rt              2024.2.0
dpctl                     0.17.0
...
fsspec                    2024.2.0
...
intel-cmplr-lib-rt        2024.2.0
intel-cmplr-lib-ur        2024.2.0
intel-cmplr-lic-rt        2024.2.0
intel-opencl-rt           2024.2.0
intel-openmp              2024.2.0
intel-sycl-rt             2024.2.0
...
mkl                       2024.2.0
scikit-learn              1.4.2
scikit-learn-intelex      2024.5.0
tbb                       2021.13.0
tifffile                  2024.5.10
tzdata                    2024.1
```

I am using the 2024.2.0 version. Do I need a newer version???
By the way, with the example you posted I get the same error messages.

**Comment by razdoburdin** [comment]
> I am sharing with you an excerpt of `pip list`
> 
> ```
> ...
> daal                      2024.5.0
> daal4py                   2024.5.0
> ...
> dpcpp-cpp-rt              2024.2.0
> dpctl                     0.17.0
> ...
> fsspec                    2024.2.0
> ...
> intel-cmplr-lib-rt        2024.2.0
> intel-cmplr-lib-ur        2024.2.0
> intel-cmplr-lic-rt        2024.2.0
> intel-opencl-rt           2024.2.0
> intel-openmp              2024.2.0
> intel-sycl-rt             2024.2.0
> ...
> mkl                       2024.2.0
> scikit-learn              1.4.2
> scikit-learn-intelex      2024.5.0
> tbb                       2021.13.0
> tifffile                  2024.5.10
> tzdata                    2024.1
> ```
> 
> I am using the 2024.2.0 version. Do I need a newer version??? 
No, you need to use another version of API. 
just replace 
`daal_model = d4p.get_gbt_model_from_lightgbm(lgb_model)`
from your code to 
`daal_model = d4p.mb.convert_model(lgb_model)`

**Comment by GLmontanari** [comment]
latest version not working either. just checked. It's the 2024.6.0

**Comment by razdoburdin** [comment]
Hi @GLmontanari , was you able solve the problem with another variant of user-API?

**Comment by GLmontanari** [comment]
Of course I tried `daal_model = d4p.mb.convert_model(lgb_model)` and it's not working as well.

**Comment by razdoburdin** [comment]
> Of course I tried `daal_model = d4p.mb.convert_model(lgb_model)` and it's not working as well.

Could you please share the minimal model with which you are experiencing the problem?

**Comment by GLmontanari** [comment]
Wait. I got your point. This is working:
```
lgb_train = lgb.Dataset(x_train, y_train, free_raw_data=False)

params = {
    "max_bin": 256,
    "scale_pos_weight": 2,
    "lambda_l2": 1,
    "alpha": 0.9,
    "max_depth": 6,
    "num_leaves": 2**6,
    "verbose": -1,
    "objective": "multiclass",
    "learning_rate": 0.3,
    "num_class": 11,
    "n_estimators": 25,
}

lgb_model = lgb.train(params, lgb_train, valid_sets=lgb_train, callbacks=[lgb.log_evaluation(0)])
daal_model = d4p.mb.convert_model(lgb_model)
```

**Comment by GLmontanari** [comment]
Ok. So I was not understanding that `LGBMClassifier `is not supported. I can get the same result by using `lgb.train()` and specifying, for my case, `objective='multiclass'`.
Thank you!
