### ISSUE TITLE
Different results from xgboost when using daal4py converted model 

### ISSUE THREAD

**Issue by kuza55** [intel/scikit-learn-intelex#2016]
**Describe the bug**
Different results from xgboost when using daal4py converted model 

**To Reproduce**

Use the attached model: 
[model.zip](https://github.com/user-attachments/files/16769910/model.zip)

```
import numpy as np
import xgboost as xgb
import daal4py as d4p

model = xgb.Booster()
model.load_model(model_path)
daal_model = d4p.mb.convert_model(model)

inputs = np.array([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
2.1400e+02, 1.0752e+04, 1.0100e+03, 1.0000e+00, 0.0000e+00, 0.0000e+00,
0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
1.0000e+00, 0.0000e+00, 0.0000e+00]], dtype=np.float64)

prediction_probs = daal_model.predict_proba(
    inputs
)

prediction = daal_model.predict(
    inputs
)

old_prediction = self.model.inplace_predict(
    inputs
)

print(prediction_probs, prediction, old_prediction)
```

**Expected behavior**

I expect to see the same results

**Output/Screenshots**
I get different results between xbg/d4p, and the d4p probs/predictions also seem inconsistent with themselves
```
[[0.53925217 0.46074783]] [0] [0.95738953]
```

**Environment:**
 - OS: Ubuntu 22.04.2 LTS via WSL
 - Version: daal/daal4py version 2024.6.0

**Comment by razdoburdin** [comment]
Hi @kuza55,
Thanks for your report!

I have reproduced the bug on my end. We will work on a permanent fix for the issue you found, but it will take some time. As a quick workaround, you can save your model in `json` format and manually replace all values in the `feature_types` array from `int` to `float`.

Please let me know if you still encounter the problem after trying this fix.
