### ISSUE TITLE
The data preparation process of kmeans

### ISSUE THREAD

**Issue by jim0421** [intel/scikit-learn-intelex#216]
I'm investigating intel daal (run with monkey patch) and scikit-learn, whose code frames are quite similar. I'm confused why intel daal doesn't include the following operations which scikit-learn uses for more accurate distance computations.
```
# file: scikit-learn/sklearn/cluster/_kmeans.py
1004         # subtract of mean of x for more accurate distance computations
1005         if not sp.issparse(X):
1006             X_mean = X.mean(axis=0)
1007             # The copy was already done above
1008             X -= X_mean
1009
1010             if hasattr(init, '__array__'):
1011                 init -= X_mean
1012
```

**Comment by KalyanovD** [comment]
Hi @jim0421,
You are absolutely right! For now daal4py isn't centered input data. Currently we don't see that centering operation would have real impact on accuracy. Feel free ask us if this thing affects you.

**Comment by PivovarA** [comment]
Hi @jim0421 
I hope our answer helped you. Is there anything else we can help you with?
