### ISSUE TITLE
Setup coverity scan automation for C+(Cython) and Python part of project

### ISSUE THREAD

**Issue by napetrov** [intel/scikit-learn-intelex#319]
Hi,
please setup CI automation for coverity scans for C++/Python parts of project. 

There is existing project with manually scanned python part
https://scan.coverity.com/projects/daal4py

You can prepare configuration and  validate it on test project or we can work together to setup it for existing one

**Comment by chinvib66** [comment]
@napetrov I would like to take up this issue.

**Comment by napetrov** [comment]
@chinvib66  - great! would you like to setup this for existing project or just create and commit configuration that i will add afterwards?

**Comment by chinvib66** [comment]
@napetrov Thanks for assigning me!

I'd like to setup the CI on a fork, and then we can complete setup for existing project in my pull request.

**Comment by chinvib66** [comment]
@napetrov I am bit stuck regarding this task. 

In travis jobs of my fork branch, the project is being built properly for linux, but the tar file is not getting submitted to coverity api. I'll have to dig bit deep into how coverity works with travis and conda. Of course, any help is appreciated.

I am unassigning myself from this issue for the time being. In case I find a solution, and issue is still available, I'll try to submit a pr.

**Comment by napetrov** [comment]
@chinvib66  Thanks.
i don't think that build it job will work well for Python+ Cython code

https://scan.coverity.com/travis_ci

I saw an example of running it via command line - assume this can be automated - 
https://community.synopsys.com/s/question/0D53400004KuySECAZ/does-coverty-support-to-scan-cc-and-python-at-the-same-time
