### ISSUE TITLE
Make a parallel build setup.py 

### ISSUE THREAD

**Issue by PetrovKP** [intel/scikit-learn-intelex#327]
Need to parallelize the build of c ++ code when called `python setup.py`

**Comment by ritiksoni00** [comment]
i want to work but im new to coding can you refer something so that i can learn about it and fix this issue!

it will great help for ME! Thankyou

**Comment by EstablishedShark** [comment]
hi id like to take this up

**Comment by GhimBoon** [comment]
ScikitEX-Team1 is working on this.
