### ISSUE TITLE
daal4py PCA with svdDense method error in distributed mode

### ISSUE THREAD

**Issue by xwu99** [intel/scikit-learn-intelex#374]
**Describe the bug**
daal4py PCA with svdDense method error in distributed mode

**To Reproduce**
Use python code and dataset
https://drive.google.com/file/d/1Bii4qZLN-Qi6Wtjz53gYDS_vt7lKm_Ki/view?usp=sharing
And run ./run.sh in daal4py environment

**Expected behavior**
use defaultDense method in distributed mode
![image](https://user-images.githubusercontent.com/23566414/98204289-b8134180-1f70-11eb-94bc-01b5d20c662e.png)

**Output/Screenshots**
use svdDense method in distributed mode
![image](https://user-images.githubusercontent.com/23566414/98204329-cb261180-1f70-11eb-91af-6658fe12a8b7.png)

**Environment:**
 - Version: oneAPI Beta 10

**Comment by xwu99** [comment]
Also check #758

**Comment by syakov-intel** [comment]
Not relevant anymore according to the originator.
