### ISSUE TITLE
Memory leak in LogisticRegression

### ISSUE THREAD

**Issue by Alexsandruss** [intel/scikit-learn-intelex#556]
**Describe the bug**
Memory leak in daal4py.sklearn.linear_model._logistic_path_0_22.LogisticRegression was appeared in according tests in PR https://github.com/IntelPython/daal4py/pull/553.
CI link: https://github.com/IntelPython/daal4py/runs/2085105525

**To Reproduce**
1. Remove 'LogisticRegression' from BANNED_ESTIMATORS in daal4py/sklearn/test/test_memory_usage.py
2. Run test

**Expected behavior**
Absence of memory leak

**Output**

       AssertionError: Size of extra allocated memory is greater than 25% of input data:
         	Input data size: 816000 bytes
         	Extra allocated memory size: 7632826 bytes / 935.4 %
       assert 7632826 < (0.25 * 816000)

**Environment:**
 - OS: all
 - Compiler: all
 - Version: 2019.3, 2021.1, master branch

**Comment by OnlyDeniko** [comment]
https://github.com/scikit-learn/scikit-learn/issues/20061

**Comment by OnlyDeniko** [comment]
https://github.com/intel/scikit-learn-intelex/pull/654
