### ISSUE TITLE
Enable run-to-run tests

### ISSUE THREAD

**Issue by SmirnovEgorRu** [intel/scikit-learn-intelex#607]
I think these algorithms can be removed from the list, because they are stable now:

https://github.com/intel/scikit-learn-intelex/blob/eb21cd67a99427c2539cb0a852a679071f816151/daal4py/sklearn/test/test_run_to_run_stability_tests.py#L304-L321

**Comment by PetrovKP** [comment]
See here: https://github.com/intel/scikit-learn-intelex/blob/eb21cd67a99427c2539cb0a852a679071f816151/daal4py/sklearn/test/test_run_to_run_stability_tests.py#L326
