### ISSUE TITLE
Segmentation fault while getTreeState applied to the model converted from lightgbm

### ISSUE THREAD

**Issue by cmsxbc** [intel/scikit-learn-intelex#663]
**Describe the bug**
As title. 

**To Reproduce**
1. use example model from lightgbm [lightgbm simple_example](https://github.com/microsoft/LightGBM/blob/f076ca58b382fa2fb0a6d8d7367983083aed03a6/examples/python-guide/simple_example.py)
2. convert the model  and apply to getTreeState
```
d4p_model = daal4py.get_gbt_model_from_lightgbm(gbm)
daal4py.getTreeState(d4p_model, 0)
```
3.  crash here.

**Expected behavior**
No segfault or raise Exception if it's not a valid operation.

**Output/Screenshots**

![image](https://user-images.githubusercontent.com/3500109/119088178-d20f0000-ba3a-11eb-8c14-551acd91591e.png)

**Environment:**
 - OS: Ubuntu 18.04
- daal4py: 2021.2.2
- lightgbm: 3.1.1

**Comment by ShvetsKS** [comment]
@cmsxbc thanks a lot for reported bug.
Fix for cpp kernel was prepared in PR: https://github.com/oneapi-src/oneDAL/pull/1634

**Comment by ShvetsKS** [comment]
@cmsxbc Please check the fix. PR[#1634](https://github.com/oneapi-src/oneDAL/pull/1634) was merged

**Comment by cmsxbc** [comment]
@ShvetsKS It works. Thanks a lot.
