### ISSUE TITLE
Possible race condition when using get_gbt_model_from_xgboost

### ISSUE THREAD

**Issue by nikosmichas** [intel/scikit-learn-intelex#717]
**Describe the bug**
When trying to run `get_gbt_model_from_xgboost` in many processes in parallel, a race condition may happen [here](https://github.com/intel/scikit-learn-intelex/blob/f8c21bd424d2a249f5858cf69c250979f97bdaa9/src/gbt_convertors.pyx#L123-L127) when reading the text file. It is possible that the same file is deleted from another process.

**To Reproduce**
Try to run the `get_gbt_model_from_xgboost` function from multiple processes at the same time

**Expected behavior**
Processes should not be affected by each other.
I could open a PR to handle this. A unique hash could be appended to `raw.txt` to handle this, or a tempfile could be used.

**Comment by ShvetsKS** [comment]
@nikosmichas Thank a lot for reporting this bug!
Currently we are looking most applicable solution, possibly the usage of different XGBoost dump interface.

**Comment by RukhovichIV** [comment]
Thanks again for reporting the bug and sorry for the late response. The corresponding PR #750 was created - text files will no longer be used in the convertor
