### ISSUE TITLE
Improve generation of documentation (comment parser)

### ISSUE THREAD

**Issue by Alexander-Makaryev** [intel/scikit-learn-intelex#81]
Doxygen documentation witch is used in DAAL supports comments with doc strings before class members. There are only few places with such doc strings but we don't support them yet.

**Comment by Alexander-Makaryev** [comment]
We have no support of multi-line descriptions for params in templates doc strings.
There are special characters for formulas in Doxygen, we don't support them at this moment.

**Comment by fschlimb** [comment]
> Doxygen documentation witch is used in DAAL supports comments with doc strings before class members. There are only few places with such doc strings but we don't support them yet.

I suggest asking the DAAL team to convert the few occurrences into inline-comments.
