### ISSUE TITLE
Issue on page /index.html

### ISSUE THREAD

**Issue by hmartiniano** [intel/scikit-learn-intelex#856]
RandomForestClassifier fails with the following error message:

```
Traceback (most recent call last):
  File "rf_test2.py", line 14, in <module>
    clf = RandomForestClassifier(n_estimators=100, n_jobs=-1, verbose=3)
  File "/home/hugo/.miniconda3/lib/python3.7/site-packages/daal4py/sklearn/ensemble/_forest.py", line 463, in __init__
    max_samples=max_samples
TypeError: __init__() got an unexpected keyword argument 'min_impurity_split'
```

To reproduce:
```
from sklearnex import patch_sklearn
patch_sklearn()

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()
X = data.data
y = data.target

clf = RandomForestClassifier(n_estimators=100, n_jobs=-1, verbose=3)
clf.fit(X, y)
```

**Comment by napetrov** [comment]
@hmartiniano  - coudl you please share version of scikit-learn-inteex and scikit-learn packages?

**Comment by hmartiniano** [comment]
Sorry, should have included those, here you go:

scikit-learn=1.0.1=py37h51133e4_0
scikit-learn-intelex=2021.2.1=py37h89c1867_1

conda 4.10.3
python 3.7.6

**Comment by napetrov** [comment]
@hmartiniano  - thanks .  Could you please update scikit-learn-intelex to 2021.4 version that have scikit-learn 1.0 support.  2021.2.1 for sure have problems.

**Comment by napetrov** [comment]
@hmartiniano  i'm looking for users to conduct short interview to get understanding on what problems you are solving currently and how our product help you there. If you have interest - please contact me via nikolay.a.petrov@intel.com. thanks!
