### ISSUE TITLE
"ValueError: The truth value of a Series is ambiguous" with basic linear regression

### ISSUE THREAD

**Issue by mmykhaylov** [intel/scikit-learn-intelex#909]
**Describe the bug**
When running linear regression on a sample dataset, a ValueError is raised. This doesn't happen after unpatching Scikit-learn

**To Reproduce**
1. main.ipynb
```python
#%%
from sklearnex import patch_sklearn, unpatch_sklearn
patch_sklearn()
#%%
import numpy as np
import sklearn as sk
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#%%
df = pd.read_csv('cars.csv')[:-1]
#%%
from sklearn.linear_model import LinearRegression

X_1 = df[['ENGINESIZE']]
X_2 = df[['CYLINDERS']]

lr = LinearRegression()
lr.fit(pd.concat([X_1, X_2], axis=1), df[['CO2EMISSIONS']])
```
cars.csv
```csv
2.0,4,8.5,196
2.4,4,9.6,221
1.5,4,5.9,136
3.5,6,11.1,255
3.5,6,10.6,244
3.5,6,10.0,230
3.5,6,10.1,232
3.7,6,11.1,255
3.7,6,11.6,267
2.4,4,9.2,
```
2. Run all cells
3. See error after `lr.fit`

**Expected behavior**
Model is successfully trained, as it happens without patching sklearn

**Output/Screenshots**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/32168861/144926388-30e5af06-2c67-4bf9-a3fa-620c9040380a.gif)

**Environment:**
 - OS: macOS 12.0.1
 - Compiler: no idea
 - Version: 2021.4.0

**Comment by mmykhaylov** [comment]
Update, it looks like the problem is with linear regression taking more than one independent variable. Still, it is unclear why this happens

**Comment by Alexsandruss** [comment]
Reproduced. 
Error at
```
        daal4py/sklearn/_utils.py in get_dtype(X):
142         return find_common_type(X.dtypes) if is_DataFrame(X) else X.dtype
```

**Comment by Alexsandruss** [comment]
Fixed by https://github.com/intel/scikit-learn-intelex/pull/911
