### ISSUE TITLE
Missing config_context for gpu offload 

### ISSUE THREAD

**Issue by c1910475054** [intel/scikit-learn-intelex#927]
The following example can not be executed in my code as the import is not possible

![image](https://user-images.githubusercontent.com/62158578/147478685-89ffc227-8d63-49ec-8c64-b87978d44da3.png)

```
from sklearnex import patch_sklearn, config_context
patch_sklearn()

from sklearn.cluster import DBSCAN

X = np.array([[1., 2.], [2., 2.], [2., 3.],
            [8., 7.], [8., 8.], [25., 80.]], dtype=np.float32)
with config_context(target_offload="gpu:0"):
   clustering = DBSCAN(eps=3, min_samples=2).fit(X)
```

1. Create conda environment with python 3.6
2. Setup GPU with conda environment
    (https://towardsdatascience.com/setting-up-tensorflow-gpu-with-cuda-and-anaconda-onwindows-2ee9c39b5c44)
3. Install via Anaconda Cloud from Intel channel
    conda install scikit-learn-intelex -c intel
![image](https://user-images.githubusercontent.com/62158578/147479180-c803fa65-f6a5-4ebe-b15c-8b7e59da5ab4.png)
4. Install dpcpp for GPU execution
    conda install dpcpp_cpp_rt -c intel
5. Import sklearnex and config_context as shown above

Environment:
 - OS: Windows 11
 - GPU: 3070 Ti

Packages: 

scikit-learn                  0.23.2             
scikit-learn-intelex      2021.3.0        
scipy                           1.4.1       
cudatoolkit                 10.1.243    
cudnn                         7.6.5
dpcpp-cpp-rt              2021.3.0

**Comment by vlad-nazarov** [comment]
Hi, 
Scikit-learn-intelex only supports Intel GPU hardware ([sys. req. link](https://www.intel.com/content/www/us/en/developer/articles/system-requirements/system-requirements-for-oneapi-data-analytics-library.html))
```
- 6th Gen Intel® Core™ processor or higher
- Intel® Iris® Plus Graphics
- Intel® Iris® Xe Graphics
- Intel® Iris® Xe Max Graphics
- Intel® Iris® Graphics
- Intel® Iris® Pro Graphics
```

**Comment by vlad-nazarov** [comment]
config_context support was added in scikit-learn-intelex 2021.4.0, so you need to update your conda environment. The 2021.5 version of scikit-learn-intelex is now available in intel channel.

**Comment by vlad-nazarov** [comment]
I am closing the issue because there are no additional questions. If you have questions or problems, you can reopen this issue or open a new one.
