### ISSUE TITLE
Import error using `Python 3.10`

### ISSUE THREAD

**Issue by eddiebergman** [intel/scikit-learn-intelex#968]
**Describe the bug**
CC: @mfeurer
When using `python 3.10`, pip says that `daal4py` version `daal4py-2021.5.3-py39-none-manylinux1_x86_64.whl` gets downloaded, the incorrect `py<x>` version. This causes an import error [here](https://github.com/intel/scikit-learn-intelex/blob/master/daal4py/__init__.py#L30).

This came about in our [tests](https://github.com/automl/auto-sklearn/runs/5200872170?check_suite_focus=true) for autosklearn.

I can see from PyPi that there is no `py310` wheels available but I would not expect to get an older wheel version as a fallback, [PyPi releases](https://pypi.org/project/scikit-learn-intelex/#files). The normal behaviour as far as I'm aware is to get an sdist version that will then attempt to build locally. This will likely fail without the right dependancies but then at least it fails explicitly before import. For reference, here is the [releases of scikit-learn](https://pypi.org/project/scikit-learn/#files).

I'm not entirely sure what this issue is related to, I'm assuming some build step relies on an explicit python version, but it works for other python versions.

**To Reproduce**
```
# Python 3.10
pip install scikit-learn-intelex  # Downloads scikit_learn_intelex-2021.5.3-py39-none-manylinux1_x86_64.whl (69 kB)
python -c "import sklearnex"
```

**Expected behavior**
To either:
* Get a py310 wheel (not currently available)
* Default to an sdist and attempt to build locally.

**Comment by Alexsandruss** [comment]
`py310` wheel will be available in next release. We will think about possibility to add `sdist`, but currently I don't see much difficulties for its addition except requirement to download dpcpp compiler externally from setup process.

**Comment by Alexsandruss** [comment]
2021.6 release with correct py310 support is available
